# Generated by Django 3.0.7 on 2022-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201206_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weights',
            field=models.IntegerField(default=0),
        ),
    ]
